support gogc config fix #61
silenceper/gowatch pull request #62
Opened 2024-02-29 23:43 UTC by flyhope

2024-03-01 09:25 UTC, silenceper commented on gowatch.go
> +	}
这里是否考虑加一个`else`，如果设置`BuildGOGC=true`，显示打开打开就直接`GOGC=on`，避免受全局变量的影响l

2024-03-01 09:50 UTC, flyhope commented on gowatch.go
> +	}
已加

2024-03-02 11:40 UTC, silenceper approved these changes

2024-03-04 12:54 UTC, silenceper requested changes

2024-03-04 12:54 UTC, silenceper commented on gowatch.go
> -	"github.com/mitchellh/go-ps"
这个为什么移除？ci错误了

2024-03-04 13:22 UTC, flyhope commented on gowatch.go
> -	"github.com/mitchellh/go-ps"
手滑了~~

2025-03-20 12:20 UTC, merged